routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Http;
use App\Http\Controllers\HomeController;
use App\Models\UnitOfMeasure;
use Illuminate\Support\Facades\Auth;

use App\Models\Client;
use App\Models\Invoice;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/panel', function () {
    return view('admin.panel');
})->name('admin.panel');

Route::resource('clients', 'ClientController')->only(['index', 'create', 'store']);
    //->middleware(['verified']);
Route::get('invoices/{invoice}/mail', 'MailController@sendMail')->name('invoices.mail');
ROute::get('profile','ProfileController@edit')->name('profile.edit');
ROute::put('profile','ProfileController@update')->name('profile.update');
Route::get('client/{client}/edit', [\App\Http\Controllers\ClientController::class, 'edit'])->name('client.edit');
Route::post('client/{client}/update', [\App\Http\Controllers\ClientController::class, 'update'])->name('client.update');
Route::delete('client/{client}', [\App\Http\Controllers\ClientController::class, 'destroy'])->name('client.destroy');


Auth::routes([
    'verify' => true,
]);
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::get('users/{user}/assign','UserController@assingAdmin')->name('users.assign.admin');
Route::get('users/{user}/approve','UserController@approveUser')->name('users.approve');
Route::get('users/{user}/assign/admin','UserController@assingAdmin')->name('users.assign.admin');
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::get('users/{user}/assign/editor','UserController@assingEditor')->name('users.assign.editor');
Auth::routes();

Route::resource('invoices', 'InvoiceController');
Route::put('invoices/{invoice}/update', 'InvoiceController@updateDescription')->name('invoices.description.update');

Route::get('/find', ['as' => 'invoices.find', 'uses' => 'InvoiceController@find']);
Route::get('/create', function () {
    $clients = Client::all();
    return view('invoices.create')->with([
        'clients' => $clients,
    ]);
})->name('invoices.create');

Route::resource('items', 'InvoiceItemController');
Route::resource('companies','CompanyController');

Route::get('/user/register', function () {
    return view('auth.postregister');
})->name('postregister');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class Client extends Model
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;


    /**
     * @var string[]
     */
    protected $fillable = [
        'tin_jmbg',
        'activity_code',
        'company_name',
        'bank_account',
        'phone_number',
        'name',
        'surname',
        'address',
        'city',
        'email',
        'is_individual',
    ];

    public function invoices()
    {
        return $this->hasMany(Invoice::class,'client_id');
    }

}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClientRequest;
use App\Models\Client;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $clients = Client::paginate(10);
        return view('clients.index')->with([
            'clients' => $clients,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(ClientRequest $request)
    {

        $client = Client::create($request->all());
        return redirect()
            ->route('clients.index')
            ->withSuccess('The client '. $request->name.' '.$request->surname.' was created.');

    }

    /**
     * Display the specified resource.
     *
     * @param Client $client
     * @return Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Client $client
     * @return Application|Factory|View
     */
    public function edit(Client $client)
    {
        return view('clients.edit')
            ->with([
                'client' => $client,
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ClientRequest $request
     * @param Client $client
     * @return RedirectResponse
     */
    public function update(ClientRequest $request, Client $client): RedirectResponse
    {
        $data = $request->validated();

        $client->fill($data);
        $client->save();

        return redirect()->back()
            ->withSuccess('The client with id ' . $client->id . ' has been updated.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param Client $client
     * @return Response
     */
    public function destroy(Client $client): RedirectResponse
    {
        Client::where('id', $client->id)->delete();
        return  redirect()->back()
            ->withSuccess('The client with id ' . $client->id . ' has been deleted.');

    }

}

resources/views/clients/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <h1 class="text-center">@lang('create_client')</h1>
        <form method="POST" action="{{ route('clients.store') }}">
            @csrf
            <div class="form-group">
                <label for="tin_jmbg">@lang('tin_jmbg')</label>
                <input type="text" class="form-control  @error('tin_jmbg') is-invalid @enderror" id="tin_jmbg" name="tin_jmbg" value="{{ old('tin_jmbg') }}">
                @error('tin_jmbg')
                <p class="text-danger">
                    {{ $message }}
                </p>
                @enderror
            </div>

            <div class="form-group">
                <label for="activity_code">@lang('activity_code')</label>
                <input type="text" class="form-control  @error('activity_code') is-invalid @enderror" id="activity_code" name="activity_code"
                    value="{{ old('activity_code') }}">
                    @error('activity_code')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                    @enderror
                </div>
            <div class="form-group">
                <label for="company_name">@lang('company_name')</label>
                <input type="text" class="form-control  @error('company_name') is-invalid @enderror" id="company_name" name="company_name"
                    value="{{ old('company_name') }}">
                    @error('company_name')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                    @enderror
            </div>
            <div class="form-group">
                <label for="bank_account">@lang('bank_account')</label>
                <input type="text" class="form-control  @error('bank_account') is-invalid @enderror" id="bank_account" name="bank_account"
                    value="{{ old('bank_account') }}">
                    @error('bank_account')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                    @enderror
            </div>
            <div class="form-group">
                <label for="phone_number">@lang('phone_number')</label>
                <input type="text" class="form-control  @error('phone_number') is-invalid @enderror" id="phone_number" name="phone_number"
                    value="{{ old('phone_number') }}">
                    @error('phone_number')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                    @enderror
            </div>
            <div class="form-group">
                <label for="name">@lang('name')</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') }}">
                @error('name')
                <p class="text-danger">
                    {{ $message }}
                </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="surname">@lang('surname')</label>
                <input type="text" class="form-control  @error('surname') is-invalid @enderror" id="surname" name="surname" value="{{ old('surname') }}">
                @error('surname')
                <p class="text-danger">
                    {{ $message }}
                </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="address">@lang('address')</label>
                <input type="text" class="form-control  @error('address') is-invalid @enderror" id="address" name="address" value="{{ old('address') }}">
                @error('address')
                <p class="text-danger">
                    {{ $message }}
                </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="city">@lang('city')</label>
                <input type="text" class="form-control  @error('city') is-invalid @enderror" id="city" name="city" value="{{ old('city') }}">
                @error('city')
                <p class="text-danger">
                    {{ $message }}
                </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">@lang('email')</label>
                <input type="text" class="form-control  @error('email') is-invalid @enderror" id="email" name="email" value="{{ old('email') }}">
                @error('email')
                <p class="text-danger">
                    {{ $message }}
                </p>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">@lang('create_client')</button>

        </form>
    </div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.admin')
@section('content')
    @if (session('success'))
        <div class="alert alert-success d-print-none" role="alert">
            {{ session('success') }}
        </div>
    @endif
    <div class="card">
        <div class="card-body">
            <h5 class="text-center">{{ $client->name }} {{ $client->surname }}</h5>
            <form action="{{route('client.update', [$client->id])}}" method="post">
                @csrf
                @if($errors)
                @endif
                <div class="form-group">
                    <label for="tin_jmbg">Tin/jmbg </label>
                    <textarea
                        name="tin_jmbg"
                        type="text"
                        id="tin_jmbg"
                        class="form-control"
                        placeholder="{{old('tin_jmbg') ?: $client->tin_jmbg}}"
                        required
                    >{{old('tin_jmbg') ?: $client->tin_jmbg}}</textarea>
                    @if($errors->has('tin_jmbg'))
                        <div class="error text-danger" class="error">{{ $errors->first('tin_jmbg') }}</div>

                    @endif
                    <label for="activity_code">Activity Code</label>
                    <textarea
                        name="activity_code"
                        type="text"
                        id="activity_code"
                        class="form-control"
                        placeholder="{{old('activity_code') ?: $client->activity_code}}"
                        required
                    >{{old('activity_code') ?: $client->activity_code}}</textarea>
                    @if($errors->has('activity_code'))
                        <div class="error text-danger">{{ $errors->first('activity_code') }}</div>
                    @endif
                    <label for="company_name">Company name </label>
                    <textarea
                        name="company_name"
                        type="text"
                        id="company_name"
                        class="form-control"
                        placeholder="{{old('company_name') ?: $client->company_name}}"
                        required
                    >{{old('company_name') ?: $client->company_name}}</textarea>
                    @if($errors->has('company_name'))
                        <div class="error text-danger">{{ $errors->first('company_name') }}</div>
                    @endif
                    <label for="bank_account">Bank Account </label>
                    <textarea
                        name="bank_account"
                        type="text"
                        id="bank_account"
                        class="form-control"
                        placeholder="{{old('bank_account') ?: $client->bank_account}}"
                        required
                    >{{old('bank_account') ?: $client->bank_account}}</textarea>
                    @if($errors->has('bank_account'))
                        <div class="error text-danger">{{ $errors->first('bank_account') }}</div>
                    @endif
                    <label for="phone_number">Phone Number </label>
                    <textarea
                        name="phone_number"
                        type="text"
                        id="phone_number"
                        class="form-control"
                        placeholder="{{old('phone_number') ?: $client->phone_number}}"
                        required
                    >{{old('phone_number') ?: $client->phone_number}}</textarea>
                    @if($errors->has('phone_number'))
                        <div class="error text-danger">{{ $errors->first('phone_number') }}</div>
                    @endif
                    <label for="name">Name </label>
                    <textarea
                        name="name"
                        type="text"
                        id="name"
                        class="form-control"
                        placeholder="{{old('name') ?: $client->name}}"
                        required
                    >{{old('name') ?: $client->name}}</textarea>
                    @if($errors->has('name'))
                        <div class="error text-danger">{{ $errors->first('name') }}</div>
                    @endif
                    <label for="surname">Surname </label>
                    <textarea
                        name="surname"
                        type="text"
                        id="surname"
                        class="form-control"
                        placeholder="{{old('surname') ?: $client->surname}}"
                        required
                    >{{old('surname') ?: $client->surname}}</textarea>
                    @if($errors->has('surname'))
                        <div class="error text-danger">{{ $errors->first('surname') }}</div>
                    @endif
                    <label for="address">Address </label>
                    <textarea
                        name="address"
                        type="text"
                        id="address"
                        class="form-control"
                        placeholder="{{old('address') ?: $client->address}}"
                        required
                    >{{old('address') ?: $client->address}}</textarea>
                    @if($errors->has('address'))
                        <div class="error text-danger">{{ $errors->first('address') }}</div>
                    @endif
                    <label for="city">City </label>
                    <textarea
                        name="city"
                        type="text"
                        id="city"
                        class="form-control"
                        placeholder="{{old('city') ?: $client->city}}"
                        required
                    >{{old('city') ?: $client->city}}</textarea>
                    @if($errors->has('city'))
                        <div class="error text-danger">{{ $errors->first('city') }}</div>
                    @endif
                    <label for="email">Email </label>
                    <textarea
                        name="email"
                        type="text"
                        id="email"
                        class="form-control"
                        placeholder="{{old('email') ?: $client->email}}"
                        required
                    >{{old('email') ?: $client->email}}</textarea>
                    @if($errors->has('email'))
                        <div class="error text-danger">{{ $errors->first('email') }}</div>
                    @endif
                </div>
                <button class="btn btn-success">
                    Confirm
                </button>
                <a href="{{ route("clients.index",["client"=>$client->id]) }}" class="btn btn-default">Back</a>
            </form>

        </div>
    </div>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.admin')
@section('content')
    @empty($clients)
        <div class="alert alert-warning">
            @lang('empty_list')
        </div>
    @else
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="row mt-2 justify-content-left ml-2">
            @can('create-clients')
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{$clients->count()}}</h3>
                            <p>@lang('clients_on_page')</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-stalker"></i>
                        </div>
                        <a href="{{ route('clients.create') }}" class="small-box-footer">@lang('new_client')<i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            @endcan
            <!-- ./col -->
        </div>
        <div class="card">
            <div class="card-body">
                <h1 class="text-center">@lang('client_list')</h1>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <th>@lang('tin_jmbg')</th>
                    <th>@lang('activity_code')</th>
                    <th>@lang('company_name')</th>
                    <th>@lang('bank_account')</th>
                    <th>@lang('phone_number')</th>
                    <th>@lang('name')</th>
                    <th>@lang('address')</th>
                    <th>@lang('city')</th>
                    <th>@lang('email')</th>
                    @can(['edit-clients', 'delete-clients'])
                        <th>Action</th>
                    @endcan
                    </thead>
                    <tbody>
                    @foreach ($clients as $client)
                        <tr>
                            <td>{{ $client->tin_jmbg }}</td>
                            <td>{{ $client->activity_code }}</td>
                            <td>{{ $client->company_name }}</td>
                            <td>{{ $client->bank_account }}</td>
                            <td>{{ $client->phone_number }}</td>
                            <td>{{ $client->name }} {{ $client->surname }}</td>
                            <td>{{ $client->address }}</td>
                            <td>{{ $client->city }}</td>
                            <td>{{ $client->email }}</td>
                            @can(['edit-clients', 'delete-clients'])
                                <td>
                                    <form class="d-inline" method="GET"
                                          action="{{route('client.edit', ['client' => $client->id])}}">
                                        <button type="submit" class="btn btn-success w-100">Edit</button>
                                    </form> <br/> <br/>
                                    <form class="d-inline" method="POST"
                                          action="{{ route('client.destroy', ['client' => $client->id]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger w-100" onclick="return confirm('Are you sure you want delete this Client')">Delete</button>
                                    </form>
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pagination justify-content-center">
                    {{ $clients->links() }}
                </div>
            </div>
        </div>
    @endif


@endsection