routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Http;
use App\Http\Controllers\HomeController;
use App\Models\UnitOfMeasure;
use Illuminate\Support\Facades\Auth;

use App\Models\Client;
use App\Models\Invoice;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/panel', function () {
    return view('admin.panel');
})->name('admin.panel');

Route::resource('clients', 'ClientController')->only(['index', 'create', 'store']);
    //->middleware(['verified']);
Route::get('invoices/{invoice}/mail', 'MailController@sendMail')->name('invoices.mail');
ROute::get('profile','ProfileController@edit')->name('profile.edit');
ROute::put('profile','ProfileController@update')->name('profile.update');
Route::get('client/{client}/edit', [\App\Http\Controllers\ClientController::class, 'edit'])->name('client.edit');
Route::post('client/{client}/update', [\App\Http\Controllers\ClientController::class, 'update'])->name('client.update');
Route::delete('client/{client}', [\App\Http\Controllers\ClientController::class, 'destroy'])->name('client.destroy');


Auth::routes([
    'verify' => true,
]);
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::get('users/{user}/assign','UserController@assingAdmin')->name('users.assign.admin');
Route::get('users/{user}/approve','UserController@approveUser')->name('users.approve');
Route::get('users/{user}/assign/admin','UserController@assingAdmin')->name('users.assign.admin');
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::get('users/{user}/assign/editor','UserController@assingEditor')->name('users.assign.editor');
Auth::routes();

Route::resource('invoices', 'InvoiceController');
Route::put('invoices/{invoice}/update', 'InvoiceController@updateDescription')->name('invoices.description.update');

Route::get('/find', ['as' => 'invoices.find', 'uses' => 'InvoiceController@find']);
Route::get('/create', function () {
    $clients = Client::all();
    return view('invoices.create')->with([
        'clients' => $clients,
    ]);
})->name('invoices.create');

Route::resource('items', 'InvoiceItemController');
Route::resource('companies','CompanyController');

Route::get('/user/register', function () {
    return view('auth.postregister');
})->name('postregister');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable = [
        'tin',
        'name',
        'address',
        'city',
        'phone_number',
        'bank_account',
        'email',
        'deleted_at'

    ];

    public function users()
    {
        return $this->hasMany(User::class);
    }
    public function invoices()
    {
        return $this->hasMany(Invoice::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Http\Requests\CompanyUpdateRequest;
use App\Models\Company;
use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = DB::table('companies')
            ->select('companies.*')
            ->where('companies.deleted_at', '=', null)
            ->paginate(10);
        return view('companies.index')->with([
            'companies' => $companies,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        Company::create($request->all());
        return redirect()
            ->route('companies.index')
            ->withSuccess('The company ' . $request->name . ' was created.');

    }

    /**
     * Display the specified resource.
     *
     * @param Company $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Company $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('companies.edit')
            ->with([
                'company' => $company,
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Company $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyUpdateRequest $request, Company $company)
    {

        $company->update([
            'tin' => $request->tin,
            'name' => $request->name,
            'address' => $request->address,
            'city' => $request->city,
            'phone_number' => $request->phone_number,
            'bank_account' => $request->bank_account,
            'email' => $request->email
        ]);
        return redirect()
            ->route('companies.index')
            ->withSuccess('The company with id ' . $company->id . ' was edited.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Company $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company): RedirectResponse
    {
        $company->delete();
        return redirect()->back()
            ->withSuccess('The company with id ' . $company->id . ' has been deleted.');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <h1 class="text-center">@lang('create_company')</h1>
        <form method="POST" action="{{ route('companies.store') }}">
            @csrf
            <div class="form-group">
                <label for="tin">@lang('vat')</label>
                <input type="text" class="form-control  @error('vat') is-invalid @enderror" id="tin"
                    name="tin" value="{{ old('tin') }}">
                @error('tin')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="name">@lang('company_name')</label>
                <input type="text" class="form-control  @error('name') is-invalid @enderror" id="name"
                    name="name" value="{{ old('name') }}">
                @error('name')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="address">@lang('address')</label>
                <input type="text" class="form-control  @error('address') is-invalid @enderror" id="address"
                    name="address" value="{{ old('address') }}">
                @error('address')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="city">@lang('city')</label>
                <input type="text" class="form-control  @error('city') is-invalid @enderror" id="city"
                    name="city" value="{{ old('city') }}">
                @error('city')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="phone_number">@lang('phone_number')</label>
                <input type="text" class="form-control  @error('phone_number') is-invalid @enderror" id="phone_number"
                    name="phone_number" value="{{ old('phone_number') }}">
                @error('phone_number')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="bank_account">@lang('bank_account')</label>
                <input type="text" class="form-control  @error('bank_account') is-invalid @enderror" id="bank_account"
                    name="bank_account" value="{{ old('bank_account') }}">
                @error('bank_account')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">@lang('email')</label>
                <input type="email" class="form-control  @error('email') is-invalid @enderror" id="email"
                    name="email" value="{{ old('email') }}">
                @error('email')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">@lang('create_company')</button>

        </form>
    </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <h1>@lang('edit_company')</h1>
        <form method="POST" action="{{ route('companies.update', ['company' => $company->id]) }}">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="id">@lang('id')</label>
                <input type="text" class="form-control" name="id" id="id" value="{{ $company->id }}" readonly>
            </div>
            <div class="form-group">
                <label for="tin">@lang('vat')</label>
                <input type="text" class="form-control @error('tin') is-invalid @enderror" name="tin" id="tin"
                    value="{{ $company->tin }}">
                @error('tin')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="name">@lang('company_name')</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                    value="{{ $company->name }}">
                @error('name')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="address">@lang('address')</label>
                <input type="text" class="form-control @error('address') is-invalid @enderror" name="address" id="address"
                    value="{{ $company->address }}">
                @error('address')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="city">@lang('city')</label>
                <input type="text" class="form-control @error('city') is-invalid @enderror" name="city" id="city"
                    value="{{ $company->city }}">
                @error('city')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="phone_number">@lang('phone_number')</label>
                <input type="text" class="form-control @error('phone_number') is-invalid @enderror" name="phone_number" id="phone_number"
                    value="{{ $company->phone_number }}">
                @error('phone_number')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="bank_account">@lang('bank_account')</label>
                <input type="text" class="form-control @error('bank_account') is-invalid @enderror" name="bank_account" id="bank_account"
                    value="{{ $company->bank_account }}">
                @error('bank_account')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">@lang('email')</label>
                <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" id="email"
                    value="{{ $company->email }}">
                @error('email')
                    <p class="text-danger">
                        {{ $message }}
                    </p>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary float-right">@lang('update')</button>
        </form>
    </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.admin')
@section('content')
    @empty($companies)
        <div class="alert alert-warning">
            @lang('empty_list')
        </div>
    @else
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="row mt-2 justify-content-left ml-2">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{$companies->count()}}</h3>
                            <p>@lang('companies_on_page')</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-stalker"></i>
                        </div>
                        <a href="{{ route('companies.create') }}" class="small-box-footer">@lang('new_company')<i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            <!-- ./col -->
        </div>
        <div class="card">
            <div class="card-body">
                <h1 class="text-center">@lang('company_list')</h1>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <th>@lang('id')</th>
                    <th>@lang('vat')</th>
                    <th>@lang('company_name')</th>
                    <th>@lang('address')</th>
                    <th>@lang('city')</th>
                    <th>@lang('phone_number')</th>
                    <th>@lang('bank_account')</th>
                    <th>@lang('email')</th>
                    <th>@lang('action')</th>
                    </thead>
                    <tbody>
                    @foreach ($companies as $company)
                        <tr>
                            <td>{{ $company->id }}</td>
                            <td>{{ $company->tin }}</td>
                            <td>{{ $company->name }}</td>
                            <td>{{ $company->address }}</td>
                            <td>{{ $company->city }}</td>
                            <td>{{ $company->phone_number }}</td>
                            <td>{{ $company->bank_account }}</td>
                            <td>{{ $company->email }}</td>
                            <td>
                                <form class="d-inline" method="GET"
                                        action="{{route('companies.edit', ['company' => $company->id])}}">
                                    <button type="submit" class="btn btn-success w-100">@lang('edit')</button>
                                </form> <br/> <br/>
                                <form class="d-inline" method="POST"
                                        action="{{ route('companies.destroy', ['company' => $company->id]) }}">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger w-100" onclick="return confirm('Are you sure you want delete this company?')">@lang('delete')</button>
                                </form>
                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pagination justify-content-center">
                    {{ $companies->links() }}
                </div>
            </div>
        </div>
    @endif


@endsection