routes/web.php
<?php

use App\Http\Controllers\ClientController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Http;
use App\Http\Controllers\HomeController;
use App\Models\UnitOfMeasure;
use Illuminate\Support\Facades\Auth;

use App\Models\Client;
use App\Models\Invoice;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/panel', function () {
    return view('admin.panel');
})->name('admin.panel');

Route::resource('clients', 'ClientController')->only(['index', 'create', 'store']);
    //->middleware(['verified']);
Route::get('invoices/{invoice}/mail', 'MailController@sendMail')->name('invoices.mail');
ROute::get('profile','ProfileController@edit')->name('profile.edit');
ROute::put('profile','ProfileController@update')->name('profile.update');
Route::get('client/{client}/edit', [\App\Http\Controllers\ClientController::class, 'edit'])->name('client.edit');
Route::post('client/{client}/update', [\App\Http\Controllers\ClientController::class, 'update'])->name('client.update');
Route::delete('client/{client}', [\App\Http\Controllers\ClientController::class, 'destroy'])->name('client.destroy');


Auth::routes([
    'verify' => true,
]);
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::get('users/{user}/assign','UserController@assingAdmin')->name('users.assign.admin');
Route::get('users/{user}/approve','UserController@approveUser')->name('users.approve');
Route::get('users/{user}/assign/admin','UserController@assingAdmin')->name('users.assign.admin');
Route::resource('users', \App\Http\Controllers\UserController::class);
Route::get('users/{user}/assign/editor','UserController@assingEditor')->name('users.assign.editor');
Auth::routes();

Route::resource('invoices', 'InvoiceController');
Route::put('invoices/{invoice}/update', 'InvoiceController@updateDescription')->name('invoices.description.update');

Route::get('/find', ['as' => 'invoices.find', 'uses' => 'InvoiceController@find']);
Route::get('/create', function () {
    $clients = Client::all();
    return view('invoices.create')->with([
        'clients' => $clients,
    ]);
})->name('invoices.create');

Route::resource('items', 'InvoiceItemController');
Route::resource('companies','CompanyController');

Route::get('/user/register', function () {
    return view('auth.postregister');
})->name('postregister');

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Invoice extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'client_id',
        'company_id',
        'invoice_number',
        'payment_term',
        'status',
        'description',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function companies()
    {
        return $this->belongsTo(Company::class);
    }
    public function invoice()
    {
        return $this->belongsTo(Client::class);
    }

    public function invoiceItems()
    {
        return $this->hasMany(InvoiceItem::class);
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Http\Requests\InvoiceRequest;
use App\Models\Company;
use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\UnitOfMeasure;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $auth = auth()->user()->company_id;
        $invoices = DB::table('invoices')
            ->join('clients', 'invoices.client_id', '=', 'clients.id')
            ->join('users', 'invoices.user_id', '=', 'users.id')
            ->select('invoices.*', 'clients.name AS c_name', 'clients.surname AS c_surname', 'users.name AS u_name', 'users.surname AS u_surname')
            ->where('invoices.company_id', '=', "$auth")
            ->paginate(10);
        return view('invoices.index')
            ->with([
                'invoices' => $invoices,
                'request' => $request
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a new blog post.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(InvoiceRequest $request)
    {
        $invoice = Invoice::create($request->validated());
        return redirect()
            ->route('invoices.show', ['invoice' => $invoice])
            ->withSuccess("The Invoice has been created!");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function show($invoice)
    {
        $invoice = Invoice::findOrFail($invoice);
        $client = Client::findOrFail($invoice->client_id);
        $user = User::findOrFail($invoice->user_id);
        $company=Company::where('id','=',$user->company_id)->get();
        $units = UnitOfMeasure::all();
        $invoice_item = InvoiceItem::where('invoice_id', '=', $invoice->id)->get();
        return view('invoices.show')->with([
            'invoice' => $invoice,
            'client' => $client,
            'user' => $user,
            'invoice_item' => $invoice_item,
            'units' => $units,
            'company' => $company,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Invoice $invoice
     * @return \Illuminate\Http\Response
     */
    public function edit(Invoice $invoice)
    {
        $clients = Client::all();
        $currentClientId = $invoice->client_id;
        $currentDateOfPayment = $invoice->payment_term;
        $currentStatus = $invoice->status;
        return view('invoices.edit')
            ->with([
                'invoice' => $invoice,
                'clients' => $clients,
                'currentClientId' => $currentClientId,
                'currentDateOfPayment' => $currentDateOfPayment,
                'currentStatus' => $currentStatus,
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Invoice $invoice
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Invoice $invoice)
    {
        $invoice->update([
            'client_id' => $request->client,
            'payment_term' => $request->payment_term,
            'status' => $request->status,
            'invoice_number'=>$request->invoice_number
        ]);
        return redirect()
            ->route('invoices.index')
            ->withSuccess('The invoice with id ' . $invoice->id . ' was edited.');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Invoice $invoice
     * @return \Illuminate\Http\RedirectResponse
     */
    public function updateDescription(Request $request, Invoice $invoice)
    {
        $invoice->update(['description' => $request->description]);
        return redirect()
            ->route('invoices.update', ['invoice' => $invoice->id])
            ->withSuccess('The invoice with id ' . $invoice->id . ' has been updated.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Invoice $invoice
     * @return \Illuminate\Http\Response
     */
    public function destroy(Invoice $invoice)
    {
        $invoice_items = InvoiceItem::where('invoice_id', '=', $invoice->id)->get();
        foreach ($invoice_items as $invoice_item) {
            $invoice_item->delete();
        }
        $invoice->delete();
        return redirect()
            ->route('invoices.index')
            ->withSuccess('The invoice with id ' . $invoice->id . ' was removed.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return Application|Factory|View
     */
    public function find(Request $request)
    {
        $auth = auth()->user()->company_id;

        $start = Carbon::parse($request->date_from)->format('Y-m-d');
        $end = Carbon::parse($request->date_to)->addDays(1)->format('Y-m-d');

        //search...
        $invoices = DB::table('invoices')
            ->join('users', 'invoices.user_id', '=', 'users.id')
            ->join('clients', 'invoices.client_id', '=', 'clients.id')
            ->select('invoices.*', 'clients.name AS c_name', 'clients.surname AS c_surname', 'users.name AS u_name', 'users.surname AS u_surname')
            ->where('clients.name', 'LIKE', '%'.$request['search'].'%')
            ->get();

        //dates and status...
        $filtered = $invoices
            ->where('company_id', '==', $auth)
            ->whereBetween('created_at', [$start, $end])
            ->whereIn('status', $request['status']);
//            ->paginate(10)

        return view('invoices.filter')
            ->with([
                'invoices' => $filtered,
                'request' => $request->all(),
            ]);
    }
}

resources/views/invoices/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row justify-content-center py-5">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">@lang('create_invoice')</div>

                    <div class="card-body">
                        <form method="post" action="{{ route('invoices.store') }}">
                            @csrf
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <input id="user_id" type="hidden"
                                           class="form-control @error('user_id') is-invalid @enderror" name="user_id"
                                           value="{{ Auth::user()->id }}" autocomplete="user_id" autofocus>
                                    @error('user_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <input id="company_id" type="hidden"
                                           class="form-control" name="company_id"
                                           value="{{ Auth::user()->company_id }}" autofocus>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <label for="client_id"
                                       class="col-md-4 col-form-label text-md-end">@lang('client')</label>

                                <div class="col-md-6">
                                    <select class="form-control" name="client_id" id="client_id">
                                        @foreach($clients as $client)
                                            <option value="{{ $client->id }}" @if($client->id == old('client_id'))
                                                selected="selected"
                                                @endif> {{ $client->company_name ?? $client->name .' '.$client->surname}}
                                            </option>
                                        @endforeach
                                    </select>

                                    @error('client_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="invoice_number"
                                       class="col-md-4 col-form-label text-md-end">@lang('invoice_number')</label>

                                <div class="col-md-6">
                                    <input id="invoice_number" type="text"
                                           class="form-control @error('invoice_number') is-invalid @enderror"
                                           name="invoice_number" value="{{ old('invoice_number') }}"
                                           autocomplete="invoice_number" autofocus>

                                    @error('invoice_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="payment_term"
                                       class="col-md-4 col-form-label text-md-end">@lang('payment_term')</label>

                                <div class="col-md-6">
                                    <input id="payment_term" type="date"
                                           class="form-control @error('payment_term') is-invalid @enderror"
                                           name="payment_term"
                                           value="{{ old('payment_term') ? old('payment_term') : date('Y-m-d') }}"
                                           autocomplete="payment_term" autofocus>

                                    @error('payment_term')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="row mb-3">
                                <label for="description"
                                       class="col-md-4 col-form-label text-md-end">@lang('description')</label>

                                <div class="col-md-6">
                                    <input id="description" type="text"
                                           class="form-control @error('description') is-invalid @enderror"
                                           name="description" value="{{ old('description') }}"
                                           autocomplete="description" autofocus>

                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="row mb-0 justify-content-center">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary justify-content-center">
                                        @lang('create_invoice')
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/invoices/filter.blade.php
@extends('layouts.admin')
@section('content')
    @empty($invoices)
        <div class="alert alert-warning">
            @lang('empty_list');
        </div>
    @else
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif

        <div class="row mt-2 justify-content-left ml-2">
            @can('create-invoices')
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{ $invoices->count() }}</h3>
                            <p>@lang('invoices_on_page')</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-compose"></i>
                        </div>
                        <a href="{{ route('invoices.create') }}" class="small-box-footer">@lang('new_invoice')<i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            @endcan
            <!-- ./col -->
        </div>
        <div class="card">
            <div class="card-body">
                <h1 class="text-center">@lang('invoice_list')</h1>
                <form method="get" action="{{ route('invoices.find') }}">
                    @csrf
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="date_from">@lang('created_at')</label>
                            <input type="date" class="form-control " name="date_from"
                                   value="{{ $request['date_from'] ? $request['date_from'] : now()->addYear(-1)->format('Y-m-d') }}"
                            >
                        </div>
                        <div class="form-group col-md-2">
                            <label for="date_to">@lang('created_to')</label>
                            <input type="date" class="form-control " name="date_to"
                                   value="{{ $request['date_to'] ? $request['date_to'] : now()->format('Y-m-d') }}"
                            >
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="cb_paid" value="paid" name="status[]"
                                @if(in_array('paid', $request['status'])) checked @endif
                            >
                            <label class="form-check-label" for="cb_paid">@lang('paid')</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="cb_not_paid" value="not paid" name="status[]"
                                   @if(in_array('not paid', $request['status'])) checked @endif
                            >
                            <label class="form-check-label" for="cb_not_paid">@lang('not_paid')</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="cb_in_progress" value="in progress" name="status[]"
                                   @if(in_array('in progress', $request['status'])) checked @endif
                            >
                            <input type='hidden' value='0' name='status[]'>
                            <label class="form-check-label" for="cb_in_progress">@lang('in_progress')</label>
                        </div>
                        <div class="form-group col-md-2">
                            <label for="search">Search by name</label>
                            <input class="form-control" type="text" name="search"
                                   value="{{ $request['search'] ? $request['search'] : "" }}"
                            >
                        </div>
                        <button type="submit" class="btn btn-secondary h-50 mt-4">@lang('find')</button>
                    </div>
                </form>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <th>@lang('invoice_number')</th>
                        <th>@lang('from')</th>
                        <th>@lang('client_name')</th>
                        <th>@lang('payment_term')</th>
                        <th>@lang('status')</th>
                        @can(['edit-invoices', 'delete-invoices'])
                            <th>@lang('action')</th>
                        @endcan
                    </thead>
                    <tbody>
                        @foreach ($invoices as $invoice)
                            <tr>
                                <td>{{ $invoice->invoice_number }}</td>
                                <td>{{ $invoice->u_name . ' ' . $invoice->u_surname }}</td>
                                <td>{{ $invoice->c_name . ' ' . $invoice->c_surname }}</td>
                                <td>{{ $invoice->payment_term }}</td>
                                <td>{{ $invoice->status }}</td>
                                @can(['edit-invoices', 'delete-invoices'])
                                    <td>
                                        <a class="btn btn-info"
                                           href="{{ route('invoices.show', ['invoice' => $invoice->id]) }}">@lang('show_more')</a>
                                        <form class="d-inline" method="POST"
                                              action="{{ route('invoices.destroy', ['invoice' => $invoice->id]) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger"
                                                    onclick="return confirm('Are you sure you want delete this item')">@lang('delete')</button>
                                        </form>
                                        </form>
                                        <form class="d-inline" method="GET"
                                              action="{{ route('invoices.edit', ['invoice' => $invoice->id]) }}">
                                            @csrf
                                            <button type="submit" class="btn btn-warning">@lang('edit')</button>
                                        </form>
                                    </td>
                                @endcan
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        @endif
    <script>

    </script>
    @endsection

resources/views/invoices/index.blade.php
@extends('layouts.admin')
@section('content')
    @empty($invoices)
        <div class="alert alert-warning">
            @lang('empty_list');
        </div>
    @else
        @if (session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="row mt-2 justify-content-left ml-2">
            @can('create-invoices')
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{ $invoices->count() }}</h3>
                            <p>@lang('invoices_on_page')</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-compose"></i>
                        </div>
                        <a href="{{ route('invoices.create') }}" class="small-box-footer">@lang('new_invoice')<i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            @endcan
            <!-- ./col -->
        </div>
        <div class="card">
            <div class="card-body">
                <h1 class="text-center">@lang('invoice_list')</h1>
                <form method="get" action="{{ route('invoices.find') }}">
                    @csrf
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="date_from">@lang('created_at')</label>
                            <input type="date" class="form-control " name="date_from"
                                   value="{{ now()->addYear(-1)->format('Y-m-d') }}"
                            >
                        </div>
                        <div class="form-group col-md-2">
                            <label for="date_to">@lang('created_to')</label>
                            <input type="date" class="form-control " name="date_to"
                                   value="{{ now()->format('Y-m-d') }}"
                            >
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="cb_paid" value="paid"
                                   name="status[]" >
                            <label class="form-check-label" for="cb_paid">@lang('paid')</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="cb_not_paid" value="not paid"
                                   name="status[]">
                            <label class="form-check-label" for="cb_not_paid">@lang('not_paid')</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="cb_in_progress" value="in progress"
                                   name="status[]">
                            <label class="form-check-label" for="cb_in_progress">@lang('in_progress')</label>
                            <input type='hidden' value='0' name='status[]'>
                        </div>
                        <div class="form-group col-md-2">
                            <label for="search">Search by name</label>
                            <input class="form-control" type="text" name="search" placeholder="Search by Name">
                        </div>
                        <button type="submit" class="btn btn-secondary h-50 mt-4">@lang('find')</button>
                    </div>
                </form>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <th>@lang('invoice_number')</th>
                    <th>@lang('from')</th>
                    <th>@lang('client_name')</th>
                    <th>@lang('payment_term')</th>
                    <th>@lang('status')</th>
                    @can(['edit-invoices', 'delete-invoices'])
                        <th>@lang('action')</th>
                    @endcan
                    </thead>
                    <tbody>
                    @foreach ($invoices as $invoice)
                        <tr>
                            <td>{{ $invoice->invoice_number }}</td>
                            <td>{{ $invoice->u_name . ' ' . $invoice->u_surname }}</td>
                            <td>{{ $invoice->c_name . ' ' . $invoice->c_surname }}</td>
                            <td>{{ $invoice->payment_term }}</td>
                            <td>{{ $invoice->status }}</td>
                            @can(['edit-invoices', 'delete-invoices'])
                                <td>
                                    <a class="btn btn-info"
                                       href="{{ route('invoices.show', ['invoice' => $invoice->id]) }}">@lang('show_more')</a>
                                    <form class="d-inline" method="POST"
                                          action="{{ route('invoices.destroy', ['invoice' => $invoice->id]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger"
                                                onclick="return confirm('Are you sure you want delete this item')">@lang('delete')</button>
                                    </form>
                                    </form>
                                    <form class="d-inline" method="GET"
                                          action="{{ route('invoices.edit', ['invoice' => $invoice->id]) }}">
                                        @csrf
                                        <button type="submit" class="btn btn-warning">@lang('edit')</button>
                                    </form>
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pagination justify-content-center">
                    {{ $invoices->links() }}
                </div>
            </div>
        </div>
    @endif
@endsection